# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58743be648e7ad56d0778b0619735e2a7ab79045a70c7656848de3e704662e5da64e0028b01bd9e8a1441c96ab523a08824ecfa09f15ee3fbe0dbeb7f5ffb063

test:
  secret_key_base: 01e6e810fddf0d05ece3eac84dbf6ad4a7d8c4be1f0f4a85df8e1ca940eb6ad9f2899173c300f8c5537417081c4ffc0244f2e8964470642566daaa1ed4b37fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
